### ISSUE TITLE
updateValidators() should should be "pure"

### ISSUE THREAD

**Issue by johannbarbie** [parsec-labs/parsec-node#36]
we need to be able to sync to the top of the chain (arrive at same validator set) without touching the parent chain.

`bridge.methods.lastCompleteEpoch()` in *updateValidators.js* fetches data "from the future" during sync, if reading form the parent chain.

**Comment by sunify** [comment]
How can we achieve this? We can't rely on height, because `epochLength` can be changed, right?

**Comment by johannbarbie** [comment]
good question. the cumbersome way would be to model all events that change `epochLength` as transactions and keep the state in tendermint. but i'm kind of lazy to do that.

**Comment by sunify** [comment]
It's probably wouldn't be a problem if #42 works fine, no?
