### ISSUE TITLE
HTTPS support for JSON RPC

### ISSUE THREAD

**Issue by sunify** [parsec-labs/parsec-node#52]

**Comment by johannbarbie** [comment]
how does geth solve this issue? isn't it, that you just have to put an ssl-terminating server in from of it?

**Comment by sunify** [comment]
Yeah, you're right. So should we recommend the same (and do for our testnet)?
If so, would be good to put the mini-instruction to docs.

Actually, it not so hard to do that with express, but we need to figure out how to pass the config and other stuff like that

**Comment by johannbarbie** [comment]
i'm ok either way. i was always annoyed about geth not allowing to configure ssl.
at the same time, i guess there are a million ways to leak an ssl certificate, if running insecure software.

**Comment by sunify** [comment]
Yeah, probably we don't want to think about such stuff. Let's not complicate our life (there are tons of things we need to do) and just put some note/page to docs.

I'll try to setup nginx for alice's node

**Comment by johannbarbie** [comment]
the other option would be to create a load balancer on AWS, it has a ssl certificate configured already.

**Comment by sunify** [comment]
https://github.com/parsec-labs/parsec-node/commit/f1230fdc97e125a74f44d4ae729d56738ae5e3e9
