### ISSUE TITLE
Change default RPC ports

### ISSUE THREAD

**Issue by sunify** [parsec-labs/parsec-node#56]
To avoid confusion with geth node

**Comment by troggy** [comment]
*9*545 ?

**Comment by troggy** [comment]
ops.. 9545 is used by `truffle develop`
https://github.com/parsec-labs/parsec-contracts/wiki/Setting-up-local-development-environment#deploying-smart-contracts

**Comment by troggy** [comment]
How about this
http: 8645
ws: 8646

**Comment by sunify** [comment]
:-) Looks good
